### ISSUE TITLE
share button from the photo gallery

### ISSUE THREAD

**Issue by drhazrd** [sourcesync/MME_Apps#28]
i am including a link to the issue in app mode that is problematic.
When in app mode (the release mode) the program doesn't share the photo from the gallery.
https://drive.google.com/file/d/0Byu07H2MBE0dS0FJNGxLbkc1SUk/edit?usp=sharing

**Comment by sourcesync** [comment]
Thanks for the detailed bug report.  I reproduced it, found the bug, and its fixed the for the next build.
